### ISSUE TITLE
Desktop freezes or crashes after deleting an "Empty File" just created & moved in grid mode

### ISSUE THREAD

**Issue by fossfreedom** [spheras/desktopfolder#238]
Git Master - UB 18.04 Virtualbox

1. Clean desktop - i.e. no .desktopfolder in  ~/Desktop
2. run com.github.spheras.desktopfolder from a command line to start
2. Right Click - properties - Grid
3. Right Click - New file
4. Click elsewhere to accept the new file name.
5. move that file to a new Grid position
6. Press the Delete key

The desktop will either crash or freeze.

```
** (com.github.spheras.desktopfolder:4738): CRITICAL **: 11:42:14.178: desktop_folder_item_settings_set_x: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:4738): CRITICAL **: 11:42:14.179: desktop_folder_item_settings_set_y: assertion 'self != NULL' failed

** (com.github.spheras.desktopfolder:4738): CRITICAL **: 11:42:14.179: desktop_folder_folder_settings_set_item: assertion 'item != NULL' failed
Gdk-Message: 11:42:14.208: com.github.spheras.desktopfolder: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

```

**Comment by spheras** [comment]
I did some changes to the master. It seems it is solved here, but a check is needed because it is difficult to reproduce (sometimes occurs, sometimes no).  Could you do some tests?

**Comment by fossfreedom** [comment]
hmm - still getting crashes after creating a folder - moving it and deleting it.

Not sure the G_MESSAGES_DEBUG or the valgrind is useful but I've attached them anyway.

```
(com.github.spheras.desktopfolder:14482): Gtk-DEBUG: 14:57:41.474: Connecting to session manager
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.475: Application.vala:99: startup event
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.475: Application.vala:86: activate event
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.476: Application.vala:239: show_desktoppanel: true
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: FolderManager.vala:216: Monitoring: /home/dad/Desktop
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: DesktopWindow.vala:97: trying to hide
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: DesktopManager.vala:83: hide_items false
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: DesktopManager.vala:84: hiding items
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: FolderManager.vala:1015: >>>>>>>>>>> INIT _sync_files for Panel: 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.529: DesktopManager.vala:126: DESKTOP SIZE CHANGED! (0,0) (1920,965)
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.533: Application.vala:571: Monitoring: /home/dad/Desktop

** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.541: FolderManager.vala:1023: >>>>>>>>>>>>>>>>>>>>>>>RESTARTING _sync_files 0 times for Panel 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.541: DesktopWindow.vala:97: trying to hide
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.542: DesktopManager.vala:83: hide_items false
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.542: DesktopManager.vala:84: hiding items
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:41.542: FolderManager.vala:1191: >>>>>>>>>>> END _sync_files for Panel: 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:42.077: Application.vala:637: desktop_visible is now true
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:42.077: DesktopWindow.vala:94: refresh, icons enabled and desktop visibility = true
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.739: FolderManager.vala:1015: >>>>>>>>>>> INIT _sync_files for Panel: 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.739: FolderManager.vala:1023: >>>>>>>>>>>>>>>>>>>>>>>RESTARTING _sync_files 0 times for Panel 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.740: FolderManager.vala:216: Monitoring: /home/dad/Desktop
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.767: DesktopWindow.vala:94: refresh, icons enabled and desktop visibility = true
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.768: DesktopWindow.vala:94: refresh, icons enabled and desktop visibility = true
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:57:50.768: FolderManager.vala:1178: >>>>>>>>>>> END _sync_files for Panel: 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:58:01.573: FolderSettings.vala:556: Alert! does not exist: /home/dad/Desktop//untitled folder
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:58:01.578: FolderManager.vala:1015: >>>>>>>>>>> INIT _sync_files for Panel: 
** (com.github.spheras.desktopfolder:14482): DEBUG: 14:58:01.579: FolderManager.vala:1023: >>>>>>>>>>>>>>>>>>>>>>>RESTARTING _sync_files 0 times for Panel 
Gdk-Message: 14:58:01.594: com.github.spheras.desktopfolder: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

[valgrind.log.txt](https://github.com/spheras/desktopfolder/files/2727423/valgrind.log.txt)

**Comment by spheras** [comment]
I did a minor change to solve that. I can't reproduce the problem exactly, but I found a similar problem as your description and it was solved with those changes. Please @fossfreedom , check if it was solved for you too. Thx.

**Comment by fossfreedom** [comment]
Yes!

Superb find :)
